[book]
authors = ["David Freeman, Robert Pisani, and Roger Purves"]
language = "vi"
multilingual = true 
src = "src"
title = "Statistics - 4th Edition"

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/Lucifer-02/stats-practices/tree/main/Stat/translate"
